### ISSUE TITLE
get_current_glucose_reading sometimes returns None on unsupported phones

### ISSUE THREAD

**Issue by gabe565** [gagebenne/pydexcom#11]
Hello!

Just discovered this API due to the Home Assistant component. Congrats on getting that merged in!

I had a question about `get_current_glucose_reading()`. I have an unsupported phone (OnePlus 7 Pro) and have a version of the G6 app that removes the device compatibility check. Everything works pretty well, but I've noticed that occasionally readings are a little bit delayed. Instead of coming in on perfect 5 minute intervals, sometimes I'll get a new reading after 7 minutes, then the next reading will be in 3 minutes. So in the end there weren't any missed readings, just a weird delay for a few minutes.   
I'd guess this is due to OnePlus's aggressive battery optimizations, but it still happens after disabling battery optimization so I think my device might just behave weird and there's nothing I can do about it.

Because of the delay, I constantly get `Unknown` values in Home Assistant and `NaN` readings in the mini-graph-card.

I could make a PR, but wanted to talk through it with you a little bit first.   
Do you think it would make sense to increase the timeout in `get_current_glucose_reading()` to 10 minutes?

**Comment by gabe565** [comment]
Oops, I forgot to attach a screenshot. A few of these blips are from when I was debugging this issue and restarting Home Assistant, but most are just from the delayed readings I mentioned above.

<img width="400" alt="Screen Shot 2020-07-23 at 4 22 34 PM" src="https://user-images.githubusercontent.com/7717888/88340300-3a009700-cd01-11ea-846a-986f91cb3cad.png">

<img width="460" alt="Screen Shot 2020-07-23 at 4 22 39 PM" src="https://user-images.githubusercontent.com/7717888/88340319-4127a500-cd01-11ea-82d9-068d156e5431.png">

**Comment by gagebenne** [comment]
I've heard some folks on the forums have been having similar issues. I think your solution could definitely help resolve some of those gaps, thank you!

I think originally my tight update interval was based on 1) the sensor's update interval and 2) ensuring the integration would report `unknown` when the sensor is lost / unavailable on the G6 application side of things (rather than just reporting the last known BG). I think your suggestion could uphold those requirements while smoothing out the data.

**Comment by gagebenne** [comment]
I'm going to roll this for a day or so as a custom component to make sure there aren't any unforeseen issues.

**Comment by gabe565** [comment]
Sounds good to me! Hopefully no weird problems pop up.

It makes sense to try to pull a tight window since you don't want old readings to show up if a sensor times out or something like that, but at the same time, a reading that's up to 10 minutes old shouldn't be drastically off from the current reading.

I'll run a custom version to test it out too!

**Comment by gagebenne** [comment]
Okay, seems to be fine. I will work on getting the small PR into HA later this month, and should hopefully resolve the gaps in readings you have been having.

**Comment by gabe565** [comment]
That's good to hear! Thank you!

**Comment by gagebenne** [comment]
I haven't had any issues since submitting the small PR to Home Assistant.
