### ISSUE TITLE
Issue with Dexcom integration

### ISSUE THREAD

**Issue by NicoSomerwil** [gagebenne/pydexcom#12]
Hi there,

great to see your Dexcom **integration** since HA 0.113. As my wife is diabetic for many years and is using the Dexcom G6 sensor I was very glad that there is support for it in HA. Unfortunately I can't get it working yet. When my wife add me as a follower in the iOS app I get just an e-mail which links me directly to the Dexcom Follow app. So I don't get any credentials to use within the integration. Searched, but didn't find a way to create a username and password within the mobile app.
Then I logged in at https://uam2.dexcom.com/index.html#/profile (server for people like us (from the Netherlands) outside the US). I noticed there that I could make another profile, which I did. Tried several new profiles). 
But no luck using this credentials to get the expected data from my wife's G6 sensor. The two expected entities are shown but no data. Also there is nothing (yet) in the logging. As I'm still a beginner, I guess I'm doing something wrong so maybe you are willing to point me in the right direction to get it working or help me a step further. By the way, sorry for my English, but hopefully you will get the point. Thanks for your integration, I'm sure when more and more people will discover it, it will be of great help for diabetics. 

Best Regards, Nico

![Overview_-_Home_Assistant_3](https://user-images.githubusercontent.com/20686314/88901643-547ec700-d251-11ea-8280-5e0b7fd48e1f.jpg)
![Configuration_-_Home_Assistant_2](https://user-images.githubusercontent.com/20686314/88901648-55aff400-d251-11ea-985f-7c6d0516cf0d.jpg)
![Configuration_-_Home_Assistant](https://user-images.githubusercontent.com/20686314/88901650-56488a80-d251-11ea-97ce-76d92919f361.jpg)

**Comment by gagebenne** [comment]
A few notes:

- Be sure you are using the email and password associated with the user that is logged in to the Dexcom G6 application.
- Be sure you have selected the right server in the **Integrations >> Dexcom >> Options**. I assume you are most likely the `OUS` server.
- Some people have had problems with connecting when their Dexcom passwords are entirely numeric. If you have connection issues in that case, try changing your password to something with a mix of numbers and letters.

Let me know if you still run into troubles.

**Comment by NicoSomerwil** [comment]
You are the best!! Thanks!!. Was looking for the credentials for me to follow my wife. It's working now with her e-mail and password. Sorry for not understanding it.
