### ISSUE TITLE
DEXCOM_APPLICATION_ID

### ISSUE THREAD

**Issue by MY20-PHEV** [gagebenne/pydexcom#13]
Hi,
Firstly, what a great library. Thankyou for all your hard work on this. 
I was just curious, if I wanted to create an app based on this, can you point me in the right direction as to how to get a DEXCOM_APPLICATION_ID ?
or is the application ID provided in the library ok for public use ?
Thanks in advance.

**Comment by gagebenne** [comment]
I'm not sure if I can be the one to say if it is okay for public use, but I _think_ this the `DEXCOM_APPLICATION_ID` is simply imitating the Dexcom G7 application ID.
