### ISSUE TITLE
Installation in micropython environment

### ISSUE THREAD

**Issue by RayJayVaughn** [gagebenne/pydexcom#14]
Hi there

Great Works and very useful. While I do think a Rpi 4 might be a bit oversized I am just trying installing it on an ESP32 TTGO-Board or later perhaps on a Rpi Pico - but unfortunately without success. Is there any way doing it?

Thanks in advance - and sorry, I am not really an it expert.

**Comment by test-account4** [comment]
I saw your post and did some googling after looking after the source code for this project.

I don't have the ability to test this, but I think the issue might be with the "Requests" library dependency (at a minimum).

From what I can tell, you might be able to use "urequests" library in it's place.  I'd be interested to hear your results.

https://forum.micropython.org/viewtopic.php?t=8152

**Comment by RayJayVaughn** [comment]
Hi there

Thanks for your answer. Unfortunately I am just trying my very first steps with (micro)python. I think I will not be able solving that. I just thougt that while micropython is not declared to be that different and the code is quite a short one, it should be quite easy making a python code a micropython code and install it eg on a esp32.

I still got an RPI zero W but my approach was a very simple hardware tool with low power consumption (battery/akku driven) and an eink-Display (maybe the way Ash Pucket did on Toms Hardware but just with low power consumption). Rasperry Pico might be nice as well but unfortunately running with micropython only.

**Comment by gagebenne** [comment]
I think having support for MicroPython is an interesting idea, but might lie a bit outside of the scope of this specific package. I agree that the issue likely lies with the `requests` library, but if you were really hard pressed to get this going on a microcontroller, it might be as simple as replacing the `requests` import with:

```python
import urequests as requests
```

That being said, I think it would be outside of the scope of this package, specifically.
