### ISSUE TITLE
FYI: Dexcom seems to have changed their API response yesterday

### ISSUE THREAD

**Issue by eimermusic** [gagebenne/pydexcom#15]
I am calling the "ous" endpoint and yesterday my code started failing.

A response now looks like this for me. Not sure if this is a change top all endpoints or something specific to the OUS one.
`````
{"WT":"Date(1638296642000)","ST":"Date(1638296642000)","DT":"Date(1638296642000+0100)","Value":164,"Trend":"Flat"}
`````

I have identified 2 changes to the API response. And one maybe.

1. The dates do not have backslashes around them anymore.
2. Trend is no longer a number but instead it is a word.
3. I am not sure if DT always had a timezone offset? I am in Europe and that offset is right.

**Comment by gagebenne** [comment]
Thanks for the update, I'll look into this promptly! US-based endpoint seems unchanged for now, but wouldn't be surprised if it sees these changes soon.

**Comment by gagebenne** [comment]
For my reference, the current response:
```
{'DT': '/Date(1638342842000+0000)/', 'ST': '/Date(1638360842000)/', 'Trend': 3, 'Value': 158, 'WT': '/Date(1638360842000)/'}
```

**Comment by gagebenne** [comment]
> Thanks for the update, I'll look into this promptly! US-based endpoint seems unchanged for now, but wouldn't be surprised if it sees these changes soon.

US-based endpoint saw these changes today around 5pm ET. Tests are not passing, further investigation tomorrow.

**Comment by gagebenne** [comment]
It seems the new endpoints are tweaked slightly in terms of responses for bad authentication, and those tests are failing. The core functionality of the library remains functional, as well as the exceptions. The tests need to be modified to match the new responses. A new issue will be opened to address this.
