### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by dhubbell76** [gagebenne/pydexcom#20]
It's been running great for a long time, thank you!

Now I see there's been some recent work and please redirect to link if it's already been covered.   The last time pydexcom worked for me was 12/8/2021.

**Below is the error message I'm getting now:**
pi@raspberrypi:~ $ sudo python3 bg_test.py
Traceback (most recent call last):
  File "bg_test.py", line 5, in <module>
    bg = dexcom.get_current_glucose_reading()
  File "/usr/local/lib/python3.7/dist-packages/pydexcom/__init__.py", line 198, in get_current_glucose_reading
    glucose_readings = self.get_glucose_readings(minutes=6, max_count=1)
  File "/usr/local/lib/python3.7/dist-packages/pydexcom/__init__.py", line 184, in get_glucose_readings
    glucose_readings.append(GlucoseReading(json_glucose_reading))
  File "/usr/local/lib/python3.7/dist-packages/pydexcom/__init__.py", line 44, in __init__
    self.trend_description = DEXCOM_TREND_DESCRIPTIONS[self.trend]
TypeError: list indices must be integers or slices, not str

**Here's the simple test script I've used in the past:**
`import sys
sys.path.append("/home/pi/.local/lib/python3.7/site-packages/")
from pydexcom import Dexcom
dexcom = Dexcom("username", "password")
bg = dexcom.get_current_glucose_reading()
print(bg.value)
`

**Comment by gagebenne** [comment]
Hi there! Could you verify you are running the latest version of pydexcom (0.2.2)?

**Comment by dhubbell76** [comment]
I think I'm running the latest version?  When I install, this is what I see.  Any other way to verify my version?

pi@raspberrypi:~ $ **sudo pip3 install pydexcom**
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pydexcom in /usr/local/lib/python3.7/dist-packages (0.1.4)
Requirement already satisfied: requests>=2.0 in /usr/lib/python3/dist-packages (from pydexcom) (2.21.0)

**Comment by gagebenne** [comment]
Looks like you're running `0.1.4`! No worries, `pip3 install pydexcom --upgrade` should get you back up and running!
