### ISSUE TITLE
Get only time without date?

### ISSUE THREAD

**Issue by dergraeber** [gagebenne/pydexcom#22]
Is it possible to get with "bg.time" or something else only the Time without the complete "2022-02-28" date?

**Comment by gagebenne** [comment]
Checkout the [datetime](https://docs.python.org/3/library/datetime.html)
module. That should have all that you need.

Please try and limit issues to the `pydexcom` module.

**Comment by dergraeber** [comment]
Yeah i thought i must change in the __init__.py the datetime in "self.time" but there was no change when i print "bg.time"...
But I'll keep looking at that, thanks

**Comment by dergraeber** [comment]
Okay, nvm i searched in the wrong direction... Now it works :D
