### ISSUE TITLE
Session Errors

### ISSUE THREAD

**Issue by connorgillespie** [gagebenne/pydexcom#24]
Hi, I just had a question regarding the following error. Is this something that is fixable on my end or am I being API limited? The error happens after about an hour of consistently pulling the current readings every 30 seconds. Thanks!

```
dexcom = Dexcom(self._credentials["username"], self._credentials["password"])
dexcom.create_session()  
bg = dexcom.get_current_glucose_reading()
```

![image](https://user-images.githubusercontent.com/48609720/176577814-c8450ba0-036b-4256-a810-a0209e5ad9fd.png)

**Comment by gagebenne** [comment]
I'd be surprised if it's an API rate limit. You're not pegging it at something silly like a request a second, haha.
Are you running these exact lines every 30 seconds?
```python
dexcom.create_session()  
bg = dexcom.get_current_glucose_reading()
```

**Comment by connorgillespie** [comment]
I have to agree with that because the Dexcom API has a limit of 60,000 requests per hour, so I was very confused when I saw that haha. I will remove the `create_session` call since it is unnecessary. 

Regarding the code being executed, the `bg.value` is pumped into a few different algorithms and the data is stored via MySQL. The whole script is synchronous and the goal in mind was to try to predict the next BG level with linear regression. This data would let me trigger some warning notifications in the event of a low BG level overnight. 

I already tried researching the 504 error with the MySQL connector, but no luck. I saw an older issue in here regarding a Session ID being stated as default or something along those lines. The error seemed like it was coming from this library. Any clue why?

**Comment by gagebenne** [comment]
Ah. I started picking up sessions errors this morning as well (it's been stable for 6+ months). My assumption is that the API has been tweaked. Looking into it.

**Comment by connorgillespie** [comment]
No worries and thanks for looking into it!

**Comment by chakachim** [comment]
Did anyone ever determine what the rate is? I’ve got a script that kicks off every 5 minutes and it keeps getting caught up in it

**Comment by gagebenne** [comment]
The API seems stable again. Thanks everyone!
