### ISSUE TITLE
Possible on a Pico W?

### ISSUE THREAD

**Issue by RenegadeTroll** [gagebenne/pydexcom#26]
I'm a total programing noob. :-D

But would it be at all possible to get this working on a pico w? 
Would be perfect to pair a pico w and a eInc display for a low powerd glucose monitor display

**Comment by gagebenne** [comment]
Hey, sorry I'm just getting back to you, I was out of the country traveling.

I think so. The `re` and `datetime` libraries have pretty robust uPython versions, and the `urequests` package should probably be a fine drop-in replacement.

Looks like the [documentation](https://www.raspberrypi.com/documentation/microcontrollers/micropython.html) indicates `urequests` is preinstalled.
