### ISSUE TITLE
error running sample code

### ISSUE THREAD

**Issue by rubinglen** [gagebenne/pydexcom#29]
I'm a little new to Python and trying to run the sample code, specifically:

>>> # Write to file: 
>>> bg_list = dexcom.get_glucose_readings(max_count=5)
>>> import json
>>> with open('bg_file.json', 'w') as f:
>>>     for bg in bg_list:
>>>         f.write(json.dumps(bg.json)+"\n")

When I try doing this I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
AttributeError: 'GlucoseReading' object has no attribute 'json'

**Comment by gagebenne** [comment]
Hi!

At the moment there is a discrepancy between the PyPi package (where you search when you run `pip3 install`) and this repository -- that'll change in the next release! Sorry about that!

For now, if you'd like to use the JSON functionality, you can 1) download the repository and install from source or 2) edit the `pydexcom` package install.

I'm cleaning up some other issues / code real quick before I update the package in PyPi.

**Comment by rubinglen** [comment]
ok great, i think i will just wait.  any idea on timeframe for the next release?  thanks!

**Comment by rubinglen** [comment]
how can i just print the list of values.  If I type something like: print(dexcom.get_glucose_readings(minutes=10))

It prints out  a list of objects like this:
<pydexcom.GlucoseReading object at 0x7f81562b5ee0>
<pydexcom.GlucoseReading object at 0x7f81563462b0>

**Comment by elnjensen** [comment]
You need to use the ‘value’ property of each BG.  You can do something like this:

```python
bg_list = dexcom.get_glucose_readings(minutes=10)
for bg in bg_list:
   print(bg.value)
```

**Comment by rubinglen** [comment]
I tried that and initially, which yields:

AttributeError: 'list' object has no attribute 'value'

**Comment by elnjensen** [comment]
Copy my code exactly.  The call to `get_glucose_readings` returns a _list_ of glucose reading objects. You can’t call `.value` on that list.  That’s why you need the `for` loop to step through the contents of the list, and look at those objects one by one.

**Comment by gagebenne** [comment]
Thanks @elnjensen! Any other questions you can checkout the Python docs. Unsure on timeline, probably this month!

**Comment by rubinglen** [comment]
thanks for the help, i am just starting out with python, so pretty green
