### ISSUE TITLE
Pydexcom no longer working outside US?

### ISSUE THREAD

**Issue by Rytis-J** [gagebenne/pydexcom#31]
Hello, it seems that I can no longer get my sugar values from pydexcom (ous=True).
![image](https://user-images.githubusercontent.com/72869230/192155545-7a05c539-a3fc-4050-959c-f1b1354a8aa8.png)
response: None

**Comment by Rytis-J** [comment]
My mistake, forgot to enable sharing on Dexcom app

**Comment by gagebenne** [comment]
No worries, the fact that it reports back `None` successfully is actually something I could catch and alert folks to setup Sharing.
