### ISSUE TITLE
Micropython compatability?

### ISSUE THREAD

**Issue by MatBat1117** [gagebenne/pydexcom#35]
I wanted to include this in a project of mine and wish to put it onto a Raspberry pi pico and wanted to know if this supports micropython  or if it doesn't, how difficult would it be to make it work?

**Comment by elnjensen** [comment]
This package requires `requests` and `datetime`, so you would need micropython equivalents for those.  

Try `pip install micropython-urequests` for the former. 

For the latter, it doesn't look like there's a drop-in replacement.  Look at https://docs.micropython.org/en/latest/library/time.html and you might be able to rewrite the needed time functions from `datetime` based on those primitives. I haven't looked to see what all is needed from `datetime`.
