### ISSUE TITLE
Cannot Import Dexcom

### ISSUE THREAD

**Issue by dereklum** [gagebenne/pydexcom#36]
Following successful pip install of pydexcom, Python responds with: cannot import name Dexcom. Any suggestions? Thank you!

**Comment by gagebenne** [comment]
Checkout https://github.com/gagebenne/pydexcom#usage, be sure to be following syntax:
```python
from pydexcom import Dexcom
```

**Comment by dereklum** [comment]
Thanks for your speedy reply. I had read that page previously. Which version of Python should be used? Thanks!

**Comment by gagebenne** [comment]
It currently requires Python 3.6+:
https://pypi.org/project/pydexcom/

**Comment by dereklum** [comment]
Thank you. That will be the cause of the problem! I will try again with Python 3.6.

Best regards,

Derek
