### ISSUE TITLE
Dexcom G7 Support

### ISSUE THREAD

**Issue by ib250** [gagebenne/pydexcom#37]
Hi

I was wondering, does the library support dexcom G7? I've been having some problems using it with an authentication error "password" invalid

**Comment by gagebenne** [comment]
Hi! It's a good question, one which I'm not so sure of myself. I don't have access to a G7, so I don't really have a way to test this. For your issue, be sure to use the correct region (`OUS` parameter set to `True` if you are located outside the US).

Let me know!

**Comment by ib250** [comment]
Thanks for the quick reply! I'm pretty sure I set it to the correct region ous=True (device is registered in Germany). The error response I'm getting is:
```
json: {'Code': 'AccountPasswordInvalid', 'Message': 'Publisher account password failed', 'SubCode': '<OnlineException DateThrownLocal="2023-03-29T14:28:17.02" DateThrown="2023-03-29T14:28:17.02Z" ErrorCode="AccountPasswordInvalid" Type="13" Category="4" Severity="1" TypeString="InvalidPassword" CategoryString="Validation" SeverityString="Minor" HostName="" HostIP="" Id="{f06c565b-7a09-452b-a164-ead72d70395e}" Message="Publisher account password failed" FullText="com.dexcom.udp.common.data.exception.OnlineException: Publisher account password failed" />', 'TypeName': 'FaultException'}
```
I saw in another thread that the password complexity could be an issue?

**Comment by gagebenne** [comment]
Could certainly try a password change! Also be sure that you have the Dexcom Share service setup, and you are using the user's credentials as opposed to the followers.

https://github.com/gagebenne/pydexcom#setup

**Comment by ib250** [comment]
Bumping this ☝️

**Comment by gagebenne** [comment]
Are you able to login to this website?

uam1.dexcom.com

**Comment by ib250** [comment]
> Are you able to login to this website?
> 
> 
> 
> https://uam1.dexcom.com

Sorry for the delay, unfortunately no. I'm not in the US

**Comment by gagebenne** [comment]
Ah, sorry, I think this is the OUS url:

uam2.dexcom.com

**Comment by ib250** [comment]
> https://uam2.dexcom.com

Yup, I can login yes. I've got a new device and created a new account as well, still the same issue

**Comment by ib250** [comment]
I did just notice something interesting. When I created the new account I shared my data with someone and the email came from the domain name `share2-dexcom.com` IIRC that was not the demain name the G6 emails came from. Sadly I cant replicate it because G6 follow seems to be broken in the app itself 😅

**Comment by gagebenne** [comment]
Hi @ib250 -- are you still having issues logging in? I've sadly ran out of troubleshooting idea, ha!

**Comment by ib250** [comment]
Yup, still not working. I'll have a look again and I'll let you know if I figure it out so you can update the library. I might do a PR if it's not too big a change. Thanks! I'll close this issue.
