### ISSUE TITLE
Dexcom Application Id

### ISSUE THREAD

**Issue by steven-freed** [gagebenne/pydexcom#39]
Hey I was wondering where the dexcom application id came from? Is it the iOS app id?There was another issue on this that no one ever really clearly answered.
Also is there anyway to use our own Dexcom Developer client id instead or is the share api not compatible with Dexcom developer registered apps.

**Comment by gagebenne** [comment]
It was fetched from the iOS app -- not sure if it is up to date or not though with the current application. And yep, you got it -- the Dexcom Developer API is a completely separate service they provide.

**Comment by gagebenne** [comment]
The [FAQ](https://github.com/gagebenne/pydexcom#faq) addresses why the difference. Thank you!
