### ISSUE TITLE
Accessing events

### ISSUE THREAD

**Issue by aes21** [gagebenne/pydexcom#48]
Hi,

Thanks for the great tool!

I was wondering if there is any plan to provide the ability to access the most recent event under the 'History' tab (i.e. Insulin or Meal).

Does the Dexcom Share Service provide this information? Could this API access it?

Thanks again!

**Comment by gagebenne** [comment]
I'm not sure the Dexcom Follow app displays this information, so I'd doubt that this information is available via the Dexcom Share API! I've explored quite a few of the endpoints and haven't seen anything along those lines, sorry!
