### ISSUE TITLE
TimeZone - Proper Date based on TimeZone

### ISSUE THREAD

**Issue by findthebug** [gagebenne/pydexcom#57]
Since im in Europe based with +2 Timezone i was thinking about the dates we get back from the API. We do have WT and DT. DT comes with the proper timezone, WT not. Just to understand, what date should be used? 

"Date(1696877837620)" -> WT (2h missing)
"Date(1696877837620+0200)" -> DT (in my case the correct one)

We get the DT timezone from the API, just thinking about this, is Dexcom checking the TimeZone based on what? Let's say i go to another county with another timeZone, would Dexcom return the proper TimeZone? 

If my follower is based in UK which is +1, is he get DT+1 and some follower in Swiss is getting DT+2?

Im Asking myself what way to go. Use DT or calculating proper date based on WT and local device TimeZone?

**Comment by gagebenne** [comment]
Yeah, that's tricky. I would suspect, but can't confirm, the `DT` is adjusted to the current location of the Dexcom wearer.

I think both are useful, and depend on the project. The joy of this API is you are free to make the choice, pull whatever and adjust however the `json`.

**Comment by gagebenne** [comment]
Just a few days ago (not yet pushed to PyPI, I started parsing the timezone `Date` string.

pydexcom/__init__.py#57

I think this handles everything -- a local date and time, UTC date and time, and `.timestamp()` on the `datetime` to get Unix time for either of those.

**Comment by spro** [comment]
Awesome I eagerly await the release
