### ISSUE TITLE
Circuitpython

### ISSUE THREAD

**Issue by jasonlshelton** [gagebenne/pydexcom#58]
I'm trying to modify this library to work with circuit python and hitting walls everywhere, would you consider working on a circuitpython version? 

And yes, I know this isn't an issue, more of a feature request

**Comment by eimermusic** [comment]
I made a port to Micropython that may work for you: https://github.com/eimermusic/picodex/tree/main/micropython/upydexcom

This is a "good enough for my needs" port that may need some further modifications depending on what you want to do.
