### ISSUE TITLE
CGM value for kids / linked accounts

### ISSUE THREAD

**Issue by gillesvs** [gagebenne/pydexcom#60]
Hello,

Is it possible to use your API to get a linked account values and not the main one.

More details: I create an account for me to be able to create a kid account linked to mine (as you need to be 18+ to have an account).
The dexcom G6 is linked to the kid account activated via the dexcom app (and share enable with multiple followers)

When I use your package (through Home Assistant) I get no error, by no values (as I guess it looks data for the main account which do not have any transmitter.

Data works well on "Follow" as I am able to select the account (mine or my kid).

When I look at the API documentation, I see no parameter to chosse a linked account....

Do you think there is a solution (apart creating a kid account as an adult account)?

**Comment by gagebenne** [comment]
Are you able to login using your dependent's account credentials? Seems like they should have their own.
https://www.dexcom.com/en-us/faqs/how-do-i-create-a-dependent-account

**Comment by gillesvs** [comment]
> Are you able to login using your dependent's account credentials? Seems like they should have their own. https://www.dexcom.com/en-us/faqs/how-do-i-create-a-dependent-account

Hello,
I switched back to librelink for the time being, but I will test your proposal if I use dexcom again.

Thank you for your work and your support
Regards
