### ISSUE TITLE
[Question] Why not use the Follow API?

### ISSUE THREAD

**Issue by kingst** [gagebenne/pydexcom#61]
Hello! I'm curious why you use the individual who is wearing the CGM's authentication credentials and _not_ the following users? I'm interested in setting up a service that supports features that need real-time Dexcom CGM readings and I prefer to not store people's credentials or even have auth tokens generated from their credentials, if possible. My ideal would be to have people add me as a follower and then use that account to load their data.

I'm happy to help implement this type of integration here, but I wanted to check if anyone has tried this and if so why did they not use it.

Love the project and thank you in advance for any advice you might have.

**Comment by gagebenne** [comment]
Yeah, I think if there was an easy way to retrieve values as a follower that would be ideal. Unfortunately we are developing against a black box. The follow process is relatively complex -- using a link that opens to the Dexcom Follow application... It's much more complex than logging in as the data producer, something we know how to do. Things get even more complex when a follower is following more than one producer, that is something that just can't happen when we use the producer's credentials.

An excellent idea, and if you have the means of understanding the Follow API to do so, certainly welcome to explore that.
