### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by leebara** [gagebenne/pydexcom#70]
Thanks so much for this, it's brilliant.
I am using it with magic mirror and a python script module to read the outputs.

Works perfectly.

My colleagues young daughter has type 1, and he is constantly checking his phone through the night to see if she is okay.

Now he can just glance at the nightstand with a small screen on a pi.

There was a module for magic mirror and some other scripts but none worked. 

Yours worked first time.

Again many thanks .

**Comment by gagebenne** [comment]
Most certainly welcome! Love to hear how folks are using it, and a magic mirror sounds like an awesome use case!
