### ISSUE TITLE
Read BG data for a time range

### ISSUE THREAD

**Issue by kanomade** [gagebenne/pydexcom#73]
Is it possible for this package to read blood glucose values for a given time range?  Sorry I'm not familiar with Python to be able to glean this from the code.   Perhaps the API supports it and this package doesn't take advantage of it.    Also can you point me to where I can find even some unofficial documentation of the API?

**Comment by gagebenne** [comment]
[`get_glucose_readings`](https://gagebenne.github.io/pydexcom/pydexcom.html#Dexcom.get_glucose_readings) is your best best. You can find documentation for the library above! As for documentation on the Share API -- there is none. At this point in time, the code backing this library probably serves as the most accurate picture of the Share API we have at present time.
