### ISSUE TITLE
max_count check,  and COUNT_INVALID const

### ISSUE THREAD

**Issue by jaydeedub** [gagebenne/pydexcom#8]
pi@raspinas4:~ $ diff .local/lib/python3.7/site-packages/pydexcom/__init__.py pydexcom-0.1.2.ORG/__init__.py 
168,169c168
<         #  jdw was minutes, changed to max_count
<         if max_count < 1 or max_count > 288:  
---
>         if minutes < 1 or minutes > 288:
pi@raspinas4:~ $ diff .local/lib/python3.7/site-packages/pydexcom/const.py pydexcom-0.1.2.ORG/const.py 
47c47
< ARGUEMENT_ERROR_MAX_COUNT_INVALID = "Count must be between 1 and 288"
---
> ARGUEMENT_ERROR_MAX_COUNT_INVALID = "Minutes must be between 1 and 288"

**Comment by gagebenne** [comment]
Thanks for pointing that out!
